define("exps_active", function() { return [

  ["molecular_three", "THREE"],

  ["unknown"],
  ["_test"],


  ["additive"],
  ["anemone_three", "THREE"],
  ["any_image_url"],
  ["bezier_flow"],
  ["box", "maze"],
  ["circle_packing"],
  ["circle_packing_zoom_loop"],
  ["circle_sectors"],
  ["corona_sine"],
  ["creature"],//, "creature_creator"], //, "creature_creator/creature_creator", "creature_creator/human"],
  ["cube_pixelator", "THREE", "TweenMax"],
  ["fool", "css/fool"],
  ["hexagon_tile"],
  ["isometric_cubes"],
  ["linked_line"],
  ["mandala"],
  ["maze"],
  ["maze_cube", "linked_line", "THREE"],//, "https://threejs.org/examples/js/exporters/OBJExporter.js"],//  "lib/three/OBJExporter.js", "lib/three/OrbitControls.js"],
  ["meandering_polygons"],
  ["mining_branches"],
  ["nested_rotating_polygon", "ease"],
  ["oscillate_curtain"],
  ["overflow"],
  ["pattern_check", "css/pattern_check"],
  ["pattern_circles"],
  ["perlin_grid", "THREE", "TweenMax"],
  ["perlin_leaves"],
  ["perlin_noise"],
  ["polyhedra","3d"], // 3d is not moduled!
  ["polyhedra_three", "THREE", "../lib/stemkoski/polyhedra"],
  ["pine_three","THREE"],
  ["race_lines_three", "THREE", "TweenMax"],
  ["rainbow_particles"],
  ["rectangular_fill"],
  ["recursive"],
  ["recursive_polygon"],
  ["spiral_even"],
  ["squaretracer"],
  ["synth_ambient", "Tone"],
  ["tea"],
  ["tetris_cube", "THREE", "TweenMax"],
  ["text_grid"],
  ["tunnel_tour_three", "THREE", "TweenMax"],
  ["typography"],
  ["voronoi_stripes", "voronoi"],
  ["zoned_particles"],

]});